version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 8080:8080
    networks:
      - app-network

  redis:
    image: redis:alpine
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - app-network

  webapp:
    build:
      context: "./webapp"
      dockerfile: dev.Dockerfile
    volumes:
      - ./webapp:/app
      - /app/node_modules
    ports:
      - 3000:3000
    networks:
      - app-network

volumes:
  redis-data:
    driver: local

networks:
  app-network:
    driver: bridge
